config/routes.rb
Rails.application.routes.draw do
  get 'product/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :products

  root 'product#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/available_on_validator.rb
class AvailableOnValidator < ActiveModel::EachValidator
    def validate_each(record, attr_name, value)
        if value.nil?
            # record.errors[attr_name] << (options[:message] || 'must be presented!')
            return
        end
        if value < Time.current
            record.errors[attr_name] << (options[:message] || 'must be in future!')
        end
    end
end

app/models/concerns/upc_validator.rb
class UpcValidator < ActiveModel::EachValidator
    def validate_each(record, attr_name, value)
        unless value.size == 10 or value.size == 12 or value.size == 13
            record.errors[attr_name] << (options[:message] || 'length must be 10 or 12 or 13!')
        end
    end
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :Properties
    has_many :ProductProperties

    validates :name, presence: true, uniqueness: true,
                    length: { minimum: 0, maximum: 1024 }

    validates :upc, presence: true, uniqueness: true, numericality: { only_integer: true }, upc: true

    validates :available_on, presence: true, available_on: true
end

app/models/product_property.rb
class ProductProperty < ApplicationRecord
  belongs_to :property
  belongs_to :product

  validates :value, length: { minimum: 0, maximum: 255 }
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :product

  validates :name, uniqueness: true, length: { minimum: 0, maximum: 255 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
        @products = Product.all

        @properties = ProductProperty
            .select('properties.id', 'product_properties.value', 'properties.name', 'properties.product_id')
            .joins(:property)
            .all
    end

    def show
        @product = Product.find(params[:id])
    end

    def new
        @product = Product.new
        @product.upc = 10.times.map { rand(10) }.join
    end

    def create
        @product = Product.new(product_params)

        if @product.save
            params['properties'].each do |prop|
                property = @product.Properties.create(name: prop['name'])
                @product.ProductProperties.create(property_id: property.id, value: prop['value'])
            end

            redirect_to @product
        else
            render 'new'
        end
    end

    private
        def product_params
            params.require(:product).permit(:name, :upc, :available_on, properties: [:name, :value])
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProductManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css', media: 'all' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<div class="container">
  <h1 class="title header_with_button">
    Listing Products
    <%= link_to 'New product', new_product_path, :class => 'button is-primary' %>
  </h1>
  
  <%= react_component("Search", { products_properties: JSON.parse(raw(@properties.to_json)), products: JSON.parse(raw(@products.to_json)) }) %>
</div>

<script>
console.log(<%= raw(@products.to_json) %> );

console.log(<%= raw(@properties.to_json) %> );
</script>

app/views/products/new.html.erb
<div class="container">
  <div class="columns is-centered">
    <div class="column is-half">

  <h1 class="title header_with_button">
    Product
    <%= link_to 'Back', products_path, :class => 'button is-secondary' %>
  </h1>

<% if @product.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@product.errors.count, "error") %> prohibited
        this product from being saved:
      </h2>
      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<%= form_with scope: :product, url: products_path, local: true do |form| %>
  <div class="field">
    <%= form.label :name, :class => 'label' %>
    <div class="control">
      <%= form.text_field :name, :class => 'input' %>
    </div>
  </div>
 
  <div class="field">
    <%= form.label :upc, :class => 'label' %>
    <div class="control">
      <%= form.text_field :upc, :class => 'input' %>
    </div>
  </div>
 
  <div class="field">
    <%= form.label :available_on, :class => 'label' %>
    <div class="control">
      <%= form.date_field :available_on, :class => 'input' %>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-label is-normal">
      <label class="label">Property</label>
    </div>
    <div class="field-body">
      <div class="field">
        <p class="control is-expanded">
          <%= text_field_tag("properties[][name]", "", class: 'input', placeholder: 'Name') %>
        </p>
      </div>
      <div class="field">
        <p class="control is-expanded">
          <%= text_field_tag("properties[][value]", "", class: 'input', placeholder: 'Value') %>
        </p>
      </div>
    </div>
  </div>
  <%= react_component("ProductProperty") %>

  <p>
    <%= form.submit :class => 'button is-primary' %>
  </p>

<% end %>
</div>
</div>
</div>

app/views/products/show.html.erb
<div class="container">
  <div class="columns is-centered">
    <div class="column is-half">
      <h1 class="title header_with_button">
        Product
        <%= link_to 'Back', products_path, :class => 'button is-secondary' %>
      </h1>

      <div class="field">
        <label class="label">Name:</label>
        <div class="control">
          <input class="input" value="<%= @product.name %>" readonly>
        </div>
      </div>
      
      <div class="field">
        <label class="label">UPC:</label>
        <div class="control">
        <input class="input" value="<%= @product.upc %>" readonly>
        </div>
      </div>

      <div class="field">
        <label class="label">Available on:</label>
        <div class="control">
          <input class="input" value="<%= @product.available_on %>" readonly>
        </div>
      </div>
    </div>
  </div>

</div>